apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-tls
spec:
  secretName: backend-tls
  dnsNames:
  - example.com
  - www.example.com
  # Issuer references are always required.
  issuerRef:
    name: testissuer
